### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by JulianBarat** [IntegratedTurtle/Rocketdustry#5]
nach git fetch, git pull und cargo run kommt folgender Error:
```
warning: unused manifest key: toolchain
   Compiling bevy_render v0.11.3
   Compiling bevy_audio v0.11.3
   Compiling umath v0.0.7
error[E0554]: `#![feature]` may not be used on the stable release channel
  --> /Users/name/.cargo/registry/src/index.crates.io-6f17d22bba15001f/umath-0.0.7/src/lib.rs:10:12
   |
10 | #![feature(core_intrinsics)]
   |            ^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `umath` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...


```

**Comment by JulianBarat** [comment]
Falls jemand die nightly installiert hat aber es Systemweit verwendet einfach statt `cargo run` `cargo run +nightly` verwenden.

**Comment by JulianBarat** [comment]
Funktioniert doch nicht...

**Comment by Bkeinn** [comment]
Also Funktioniert es algemien nicht oder `cargo run +nightly` nicht

**Comment by Bkeinn** [comment]
Dann musst du das neue Output reinschicken

**Comment by JulianBarat** [comment]
Ich hatte zwei conflicting Rust-Installationen, die ursprüngliche Methode funktioniert. Tipp für Mac-User, checken ob es eine Rust-Installation von Homebrew gibt, wenn ja per `brew uninstall Rust` löschen.

**Comment by Bkeinn** [comment]
Schreib das ins wiki
