### ISSUE TITLE
Fix spelling mistakes in Variables

### ISSUE THREAD

**Issue by Bkeinn** [IntegratedTurtle/Rocketdustry#7]
Please fix the spelling mistakes in the code.
How to:
1. CLone the repo and make sure it is running correctly
2. Look though the  code
3. find one variable with spelling mistake
4. write down how to variable was written and the correct it
5. now try to compile and solve the new erros only by changing the name from the old one to the new one
6. Commit if it runns again
You could also try an replace all, but I don't know how good this works

**Comment by IntegratedTurtle** [comment]
Corrected spelling mistakes in the code.
Did NOT correct spelling mistakes in the comments.
